# Generated by Django 2.0.13 on 2023-08-07 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
            ],
            options={
                'db_table': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Ejercicios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enunciado', models.TextField()),
                ('ruta_imagen', models.TextField()),
            ],
            options={
                'db_table': 'Ejercicios',
            },
        ),
        migrations.CreateModel(
            name='Evaluaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('calificacion', models.IntegerField()),
            ],
            options={
                'db_table': 'Evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='Lecciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField()),
                ('contenido_texto', models.TextField()),
                ('ruta_imagen', models.TextField()),
                ('ruta_recurso', models.TextField()),
                ('status', models.TextField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.Categorias')),
            ],
            options={
                'db_table': 'Lecciones',
            },
        ),
        migrations.CreateModel(
            name='Progresos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('completada', models.BooleanField()),
                ('id_leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.Lecciones')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Progresos',
            },
        ),
        migrations.CreateModel(
            name='Puntuaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField()),
                ('id_leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.Lecciones')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Puntuaciones',
            },
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto_respuesta', models.TextField()),
                ('es_correcta', models.BooleanField()),
                ('id_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.Ejercicios')),
            ],
            options={
                'db_table': 'Respuestas',
            },
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.Respuestas')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Resultados',
            },
        ),
        migrations.AddField(
            model_name='evaluaciones',
            name='id_leccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.Lecciones'),
        ),
        migrations.AddField(
            model_name='evaluaciones',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ejercicios',
            name='id_leccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.Lecciones'),
        ),
    ]
